services:
  mongodb:
    image: mongo:8.0
    container_name: practice
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kirtan1986
    
    volumes:
      - practice_db:/data/db

volumes:
  practice_db: